### ISSUE TITLE
大神，怎么用？

### ISSUE THREAD

**Issue by KiritoBeater** [liyanhuadev/ObjectMapper-Plugin#1]
可否给个安装说明

**Comment by liyanhuadev** [comment]
补一下 ‘xcode source editor extension’的知识

**Comment by ghost** [comment]
Please upload compiled extension. I can't compile this for some signing reason and disabling signing didn't help either.

**Comment by lcl22hope** [comment]
maybe the signing issue problem, we could compile it, so please upload a compiled version, thanks so mush!

**Comment by yuanjilee** [comment]
@lcl22hope  @aryaei  
  
As Apple Document say:
> Because your extension runs in Xcode, you must enable development signing for each target in your project. 

so, you should select a sign for the two target.
I chooes my personl sign for temporary

![image](https://user-images.githubusercontent.com/9959986/29492297-dcba10ea-85a9-11e7-9ce2-78394b1464c0.png)

**Comment by kkkelicheng** [comment]
@yuanjilee 
That need Mac developer .....
🤣

**Comment by yanfeng42** [comment]
@kkkelicheng The MAc developer account is not required. The key point is: To modify the certificate of ObjectMapper-Plugin and ExCommand at the same time

**Comment by yanfeng42** [comment]
@KiritoBeater

用法参考: 

[https://www.jianshu.com/p/9c9d0fcc62cc](https://www.jianshu.com/p/9c9d0fcc62cc)


Editor 菜单 --> Excommand

```
开发时，插件只要运行起来，我们就可以在Xcode菜单栏中的Editor最下面看到插件名字和使用，但一旦停止运行，插件并不会常驻Xcode供我们使用。
但是，我们可以这样做: 找到Products文件夹下生成的的.app文件

右键点击此文件 -> “在Finder中显示” -> 将这个.app文件拷贝到你或者小伙伴电脑上的"应用程序"里 :

在“应用程序”中双击.app文件运行。然后，打开“系统偏好设置” -> "扩展" -> "Xcode Source Editor" -> 确认插件名字前已打钩 -> 此时Xcode中菜单栏Editor下的插件虽然显示，但是为灰色，无法点按，所以要 -> 重启Xcode -> 大功告成！

作者：麟young
链接：https://www.jianshu.com/p/9c9d0fcc62cc
來源：简书
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
```

**Comment by KiritoBeater** [comment]
Thanks for help. So, I think it should be close.
